# Generated by Django 6.0.7 on 2026-07-12 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar', models.CharField(max_length=5)),
                ('adversario', models.CharField(max_length=100)),
                ('etapa', models.CharField(choices=[('GRUPO I', 'Grupo I'), ('16-AVOS', '16-Avos'), ('OITAVAS', 'Oitavas'), ('QUARTAS', 'Quartas'), ('SEMI_FINAL', 'Semi-final'), ('Final', 'Final')], default='', max_length=100)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('colocacao', models.CharField(max_length=1)),
                ('gols', models.CharField(max_length=3)),
                ('gols_sofridos', models.CharField(max_length=3)),
                ('jogos', models.CharField(max_length=1)),
            ],
        ),
    ]
