# Generated by Django 6.0.7 on 2026-07-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='colocacao',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='gols',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='gols_sofridos',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='jogos',
        ),
    ]
