# Generated by Django 6.0.7 on 2026-07-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0003_alter_campanha_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='etapa',
            field=models.CharField(choices=[('GRUPO I', 'Grupo I'), ('16-AVOS', '16-Avos'), ('OITAVAS', 'Oitavas'), ('QUARTAS', 'Quartas'), ('SEMI FINAL', 'Semi final'), ('Final', 'Final')], default='', max_length=100),
        ),
    ]
