# Generated by Django 6.0.7 on 2026-07-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0004_alter_campanha_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquista', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
                ('ano', models.CharField(max_length=400)),
            ],
        ),
    ]
