# Generated by Django 6.0.7 on 2026-07-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0005_titulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='etapa',
            field=models.CharField(choices=[('Grupo I', 'Grupo I'), ('16-Avos', '16-Avos'), ('Oitavas', 'Oitavas'), ('Quartas', 'Quartas'), ('Semi Final', 'Semi final'), ('Final', 'Final')], default='', max_length=100),
        ),
    ]
