# Generated by Django 6.0.7 on 2026-07-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0006_alter_campanha_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulos',
            name='importancia',
            field=models.CharField(choices=[('evento ', 'evento'), ('evento grande', 'evento grande')], default='', max_length=100),
        ),
    ]
