# Generated by Django 6.0.7 on 2026-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0008_participacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='ano',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='colocacao',
            field=models.CharField(choices=[('Fase de grupos', 'Fase de grupos'), ('Oitavas', 'Oitavas'), ('Quartas', 'Quartas'), ('4º Lugar', '4º Lugar'), ('3º Lugar', '3º Lugar'), ('Vice-campeã', 'Vice-campeã'), ('🏆 Campeã', '🏆 Campeã')], default='', max_length=100),
        ),
    ]
