# Generated by Django 6.0.7 on 2026-07-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0009_alter_participacao_ano_alter_participacao_colocacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
    ]
