# Generated by Django 6.0.7 on 2026-07-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0010_curiosidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(max_length=100)),
            ],
        ),
    ]
