# Generated by Django 6.0.7 on 2026-07-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franca', '0011_elenco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='colocacao',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Fase de grupos', 'Fase de grupos'), ('Oitavas', 'Oitavas'), ('Quartas', 'Quartas'), ('4º Lugar', '4º Lugar'), ('3º Lugar', '3º Lugar'), ('Vice-campeã', 'Vice-campeã'), ('🏆 Campeã', '🏆 Campeã')], default='', max_length=100),
        ),
    ]
